### ISSUE TITLE
Creating links to upstream repos with no permission

### ISSUE THREAD

**Issue by jeremypoulter** [1egoman/backstroke#45]
I am trying to use Backstroke to auto sync a fork of a repository I do not have permission to create a web hook on, ie repo a (no permission) -> repo b (my fork).

I think I can use IFTTT to monitor the upstream commit RSS feed and trigger the Backstroke link but I am unable to create the link as I get an error creating the webhook on the upstream repo. 

Is there a way to ignore this? Is there a better solution?

**Comment by 1egoman** [comment]
@jeremypoulter There's not a good way to solve this unfortunately with the Backstroke that's out in the wild right now. A workaround using some older code:
- Add [Backstroke classic](https://github.com/1egoman/backstroke#use-backstroke-classic) to your fork.
- Make a commit and take a look at the webhook logs for backstroke classic.
- From another source (IFTTT, etc), duplicate the request that the webhook sent (same headers, same body, etc)
- When that request is made externally, Backstroke Classic will look at the body and use that to determine which "repo" the request is associated with (your fork). Since the repo is a fork, Backstroke is smart enough to realize this and sync changes from the upstream.

Let me know if that works!

**Comment by jeremypoulter** [comment]
Thanks, however I am not sure Backstroke classic will work for my case either. I need to create the PR on a specific branch, can that be done with Backstroke classic?

**Comment by 1egoman** [comment]
@jeremypoulter Your right, Backstroke classic can't do that. I'm not sure if this is possible in the current incarnation of backstroke. If you'd like to try and hack it together, the relevant code is [here](https://github.com/1egoman/backstroke/blob/909fc06814c0fe2ff8fa9618abf7126c4fcb401e/src/helpers/addWebhooksForLink.js#L11-L44) (Whether you want to fork and make the change in a hacky fashion for your own use case or try and make it resilient and merge back would be up to you.)

Other than the above, I'm out of ideas.
