### ISSUE TITLE
Avoid merge commit

### ISSUE THREAD

**Issue by Muffo** [1egoman/backstroke#8]
Out of interest, is there a way to remove the "merge" commit that is automatically created after accepting  a pull request?

**Comment by 1egoman** [comment]
@Muffo Since Backstroke creates normal pull requests to merge upstream changes, by default there isn't a way by just straight merging. As an alternative, you could [squash and merge](https://github.com/blog/2141-squash-your-commits) - then, you'd only get one new commit instead of one for each new change. If you're thinking of something like a rebase, I don't think you can do that from the web.

**Comment by Muffo** [comment]
Hi @1egoman 

Thanks a lot for the answer! I understand now, this is more a limitation of Github instead of backstroke.
I wonder if these extra commits create any problem when you implement new features in your fork and create a pull request to get them merged in the upstream repo.

**Comment by 1egoman** [comment]
@Muffo From the (minimal) testing that I've done, these extra commits haven't caused anything strange to happen that requires manual intervention (like a merge conflict).

If you're diverging from upstream far enough that there's merge conflicts to resolve, it's probably not a big deal for you to fix it locally.

**Comment by Muffo** [comment]
Perfect! Many thanks for the support :+1:
